angular.module('caroline-website',
    [
        'ui.router',
        'ngRoute',
        'caroline-website.SidebarModule',
        'caroline-website.HomeModule',
        'caroline-website.ProjectModule',
        'caroline-website.ProfessionalModule',
        'caroline-website.FooterModule'
    ]);