angular.module('caroline-website',
    [
        'ui.router',
        'ui.bootstrap',
        'ngRoute',
        'ngSanitize',
        'emoji',
        'caroline-website.SidebarModule',
        'caroline-website.HomeModule',
        'caroline-website.ProjectModule',
        'caroline-website.ReadingModule',
        'caroline-website.GithubModule',
        'caroline-website.D3Module',
        'caroline-website.ProfessionalModule',
        'caroline-website.FooterModule'
    ]);