angular.module('caroline-website',
    [
        'ui.router',
        'ui.bootstrap',
        'ngRoute',
        'caroline-website.hire-me-module',
        'caroline-website.navigation-module',
        'caroline-website.SidebarModule',
        'caroline-website.home-module',
        'caroline-website.ProjectModule',
        'caroline-website.ReadingModule',
        'caroline-website.ProfessionalModule',
        'caroline-website.footer-module'
    ]);
